### PR TITLE
Fixed get_selling_price function for boolean comparision issue

### PR DESCRIPTION
**Pull request by mk-khan**
updated all scripts to do a boolean compare instead of boolean and integer

### CODE REVIEW

**Comment by mixerp** [comment]
Hi,

I am closing this pull request and instead submitting a patch because this PR changes the older version of database script. Even though there is a bug in older version, we should only change the datbase update script.

**Comment by mk-khan** [comment]
Hi,

I was pretty sure, I did corrected the values in more files then I should
have could you please help me to understand what files should I be updating
everytime I find an issue..? According to your comments it looks like I
should only update the updates script, but I am lost when I see update
scripts for 1 1.1v and 2.x.. What's the naming convention..? Thanks

**Comment by mk-khan** [comment]
@binodnp could you please help me with few things here, so when i issue is found in function, view script which scripts needs to be updated at this time ? Why there are more than one update scripts ? 1 1.x and so on ... ? 

Another general question i have is with updating live sites with latest code and scripts. How can i update a live site after this fix is applied to the master branch .. Thank you

**Comment by mixerp** [comment]
1. In MixERP, every database schema scripts must have a version number.
2. Each new update must be contained in a separate directory placing the database scripts. 
3. Currently, we don't have more than one update script as you've mentioned.

https://github.com/mixerp/sales/tree/master/db/SQL%20Server

4. If there is more than one database update available, updates should be installed sequentially by version numbers.
5. A database update should never delete any data.
6. A database update should not produce any error even when executed for several times.

As you can see in the link below, this file is an update script which updates `2.0` database version to `2.1`.

https://github.com/mixerp/inventory/blob/master/db/PostgreSQL/2.1.update/inventory-2.1.update.sql

**Updating an existing site:**
1. Replace the MixERP/Frapid ASP.net files. This includes individual db folders, as well.
2. Use the `Updater` app to install database updates.

**Comment by mk-khan** [comment]
Thanks mate!! So to sump it up, Next time I have a db update as a PR, I
just create a new update file as version 2.2 or 2.x and include the script
in it...?

Also, when you said replace MixERP/Frapid files for code files, if i have a
Tenent created then do I have make sure that does not get replaced..? Also,
configuration files which are updated do they need to be left alone as well
when you copy over the release code to the live site folder (website
virtual directory root path)... Is that correct understanding..? Or am I
still missing something..?

One another question I have is, how we can keep upto date with the latest
fixes and changes happening across these multiple repositories..? Basically
if there is a code fix done on finance repo.. How do I know, i should
update website for the same..?

There are few design improvements and suggestions we have for few things in
current system, is there a conference or meeting you guys do so the
open-source team can discuss the priority and make sure we are all on the
same page..?

Sorry for long list of questions, bare with me few more weeks and hopefully
we will be up and running with everything to contribute much faster soon..
Its just the understanding gap at this time.. Which slowing me down..

Thanks again for your previous answer much appreciated

**Comment by mixerp** [comment]
Please make sure that you need to document (and back up) the overridden views (if any):

https://www.youtube.com/watch?v=DOaV_fPGoTQ

Similarly, configuration files should be backed up as well.

Database updates should only go to the update folder having the highest version number. If for some reason there isn't an update folder in a certain module, please collaborate with us in our forums and we will create an update folder for you.

Installing update is simple:

On production:

1. Update the published files in IIS. Restore the overrides and configuration.
2. Run the module `Updates`.

On development:

1. Update the source code.
2. Run the module `Updates`.

You don't need to worry about potentially losing data by installing an update multiple times. An update in MixERP deletes nothing and is safe to use multiple times.

**Pull request closed without merging**
